name: Laravel Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1️⃣ 取得程式碼
      - uses: actions/checkout@v3

      # 2️⃣ 安裝 PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, mysqli, pdo_mysql

      # 3️⃣ 安裝 Composer 套件 (含 dev)
      - name: Install Composer dependencies
        run: composer install --working-dir=backend --no-progress --prefer-dist --ignore-platform-reqs --dev

      # 4️⃣ 設定 .env
      - name: Setup environment
        run: cp backend/.env.example backend/.env

      # 5️⃣ 產生 app key
      - name: Generate app key
        run: php backend/artisan key:generate

      # 6️⃣ 執行 migrations
      - name: Run migrations
        run: php backend/artisan migrate --env=testing

      # 7️⃣ 執行 Pest 測試
      - name: Run Pest tests
        run: php backend/vendor/bin/pest --configuration backend/phpunit.xml
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: root
